site_name: ScrAPD
pages:
  - Home: index.md
  - Guides:
    - Keeping your branch up-to-date: 'guides/update-branch.md'
  - Learning:
    - Learning resources: 'learning/learning.md'

theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple,
  logo:
    icon: supervisor_account
  feature:
    tabs: true
  favicon: 'img/favicon.ico'

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
