site_name: ScrAPD
pages:
  - Home: index.md
  - Contributor Zone:
    - RYR 3.0 concepts: 'contributor-zone/ryr3.0-concepts.md'
    - Technical Overview: 'contributor-zone/technical-overview.md'
    - Austin Design Week 2017: 'contributor-zone/adw-2017.md'
    - Services & costs: 'contributor-zone/services-costs.md'
    - Project Planning Canvas: contributor-zone/goals-strategy.md
  - Guides:
    - Setting up a local environment: 'guides/setup-full-environment.md'
    - Keeping your branch up-to-date: 'guides/update-branch.md'
    - Installing Git extras: 'guides/git-extras.md'
    - Installing Hub: 'guides/install-hub.md'
    - Installing Liquidprompt: 'guides/install-liquidprompt.md'
  - Learning:
    - Learning resources: 'learning/learning.md'
  - About:
    - 'License': 'about/license.md'
theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple,
  logo:
    icon: report
  feature:
    tabs: true
  favicon: 'img/favicon.ico'

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
